In [2]:
import pandas as pd

df = pd.read_csv("latent_class_breast_cancer.csv")

In [3]:
df.shape

(569, 37)

In [7]:
df.diagnosis.value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [96]:
df.columns

Index(['Unnamed: 0', 'model_number', 'classes_number', 'radius_mean',
       'texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean',
       'compactness_mean', 'concavity_mean', 'concave_points_mean',
       'symmetry_mean', 'fractal_dimension_mean', 'radius_se', 'texture_se',
       'perimeter_se', 'area_se', 'smoothness_se', 'compactness_se',
       'concavity_se', 'concave_points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave_points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'CPROB1', 'CPROB2',
       'Class', 'diagnosis'],
      dtype='object')

In [2]:
features = [
    'radius_mean',
    'texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean',
    'compactness_mean', 'concavity_mean', 'concave_points_mean',
    'symmetry_mean', 'fractal_dimension_mean', 'radius_se', 'texture_se',
    'perimeter_se', 'area_se', 'smoothness_se', 'compactness_se',
    'concavity_se', 'concave_points_se', 'symmetry_se',
    'fractal_dimension_se', 'radius_worst', 'texture_worst',
    'perimeter_worst', 'area_worst', 'smoothness_worst',
    'compactness_worst', 'concavity_worst', 'concave_points_worst',
    'symmetry_worst', 'fractal_dimension_worst', 'CPROB1', 'CPROB2',
    'Class']

feat1 = [
#     'radius_mean',
#     'texture_mean',
#     'perimeter_mean',
    'area_mean',
   'smoothness_mean',
#    'compactness_mean', 
#    'concavity_mean',
#     'concave_points_mean',
#     'symmetry_mean',
#     'fractal_dimension_mean',
    'radius_se',
    'texture_se',
#     'perimeter_se',
#     'area_se',
#     'smoothness_se'
]
feat2 = [
#     'compactness_se',
#     'concavity_se',
#     'concave_points_se',
#     'symmetry_se',
#     'fractal_dimension_se',
#     'radius_worst',
#     'texture_worst',
#     'perimeter_worst',
      'area_worst',
#     'smoothness_worst',
#     'compactness_worst',
#     'concavity_worst',
#     'concave_points_worst',
#     'symmetry_worst',
#     'fractal_dimension_worst',
#     'CPROB1',
#    'CPROB2'
]

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split


df_sample = df.sample(200, random_state=1)
y = df_sample['diagnosis'].tolist()   
X = df_sample[feat1].to_numpy()


X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=42)
clf1 = svm.SVC(random_state=0).fit(X_train, y_train)
y_pred = clf1.predict(X_test)
print(classification_report(
    y_test,
    y_pred,
    target_names=["Happy", "Sad"]))

              precision    recall  f1-score   support

       Happy       0.96      0.90      0.93        29
         Sad       0.77      0.91      0.83        11

    accuracy                           0.90        40
   macro avg       0.87      0.90      0.88        40
weighted avg       0.91      0.90      0.90        40



In [14]:
from sklearn.metrics import confusion_matrix

#y_p = clf1.predict(X)
cm1 = confusion_matrix(y_test, y_pred, labels=["M", "B"])
print(cm1)

[[10  1]
 [ 3 26]]


In [15]:
tp = cm1[0][0]
fp = cm1[0][1]
fn = cm1[1][0]
tn = cm1[1][1]
print(f"tp={tp} fp={fp} fn={fn} tn ={tn}")
print(f'fpr={fp/(fp+tp)}')
print(f'tpr={tp/(fp+tp)}')
print(f'fnr={fn/(fn+tn)}')
print(f'tnr={tn/(fn+tn)}')

tp=10 fp=1 fn=3 tn =26
fpr=0.09090909090909091
tpr=0.9090909090909091
fnr=0.10344827586206896
tnr=0.896551724137931


In [16]:
from sklearn.ensemble import RandomForestClassifier


df_sample = df.sample(200, random_state=1)
y = df_sample['diagnosis'].tolist()   
X = df_sample[feat2].to_numpy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
clf2 =  RandomForestClassifier(max_depth=2, random_state=0).fit(X_train, y_train)
y_pred = clf2.predict(X_test)
print(classification_report(
    y_test,
    y_pred,
    target_names=["Benign", "Malicious"]
))

              precision    recall  f1-score   support

      Benign       0.93      0.97      0.95        29
   Malicious       0.90      0.82      0.86        11

    accuracy                           0.93        40
   macro avg       0.92      0.89      0.90        40
weighted avg       0.92      0.93      0.92        40



In [17]:
from sklearn.metrics import confusion_matrix

#y_p = clf1.predict(X)
cm2 = confusion_matrix(y_test, y_pred, labels=["M", "B"])
print(cm2)

[[ 9  2]
 [ 1 28]]


In [18]:
tp = cm2[0][0]
fp = cm2[0][1]
fn = cm2[1][0]
tn = cm2[1][1]
print(f"tp={tp} fp={fp} fn={fn} tn ={tn}")
print(f'fpr={fp/(fp+tp)}')
print(f'tpr={tp/(fp+tp)}')
print(f'fnr={fn/(fn+tn)}')
print(f'tnr={tn/(fn+tn)}')

tp=9 fp=2 fn=1 tn =28
fpr=0.18181818181818182
tpr=0.8181818181818182
fnr=0.034482758620689655
tnr=0.9655172413793104


In [19]:
df_c = pd.read_csv("HW.csv")

In [29]:
class1 = df_c[df_c['Class'] == 1]
class2 = df_c[df_c['Class'] == 2]

h1 = len(class1[class1['diagnosis'] == 'B'])
j1 = len(class1[class1['diagnosis'] == 'M'])

h2 = len(class2[class2['diagnosis'] == 'B'])
j2 = len(class2[class2['diagnosis'] == 'M'])
print(h1, j1, h2, j2)
print(1 - h1/j1)
print(j2/h2)

5 174 352 38
0.9712643678160919
0.10795454545454546


In [28]:
df_c

Unnamed: 0  Class diagnosis Test1 Test2
0             0      1         M     M     M
1             1      1         M     M     M
2             2      1         M     M     M
3             3      1         M     M     B
4             4      1         M     M     M
..          ...    ...       ...   ...   ...
564         564      1         M     M     M
565         565      1         M     M     M
566         566      1         M     B     M
567         567      1         M     M     M
568         568      2         B     B     B

[569 rows x 5 columns]

In [102]:
df2 = df
test_1 = []
test_2 = []
for i, row in df2.iterrows():
    test_1.append(clf1.predict(row[feat1].to_numpy().reshape(1, -1))[0])
    test_2.append(clf2.predict(row[feat2].to_numpy().reshape(1, -1))[0])

df2["Test1"] = test_1
df2["Test2"] = test_2

In [94]:
df['Class'].unique()

array([1, 2])

In [103]:
df_out = df2[["Class", "diagnosis", "Test1", "Test2"]]

In [106]:
df_out[df_out['Class']== 2]

Class diagnosis Test1 Test2
10       2         M     B     M
13       2         M     B     B
16       2         M     B     M
19       2         B     B     B
20       2         B     B     B
..     ...       ...   ...   ...
558      2         B     B     B
559      2         B     B     B
560      2         B     B     B
561      2         B     B     B
568      2         B     B     B

[390 rows x 4 columns]

In [107]:
df_out.to_csv("HW.csv")